// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOt_xYAkX5QUXeux6piTHu10_xpSD5BIA',
    appId: '1:565467298061:web:5d8e254d9a595b166ad844',
    messagingSenderId: '565467298061',
    projectId: 'e-tiket-kapal-laut',
    authDomain: 'e-tiket-kapal-laut.firebaseapp.com',
    storageBucket: 'e-tiket-kapal-laut.appspot.com',
    measurementId: 'G-WETKW8MB78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GqcPnUrfl64frmRLOqRy1oi022POckY',
    appId: '1:565467298061:android:baeaeef31fff888c6ad844',
    messagingSenderId: '565467298061',
    projectId: 'e-tiket-kapal-laut',
    storageBucket: 'e-tiket-kapal-laut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJ548vDC5UXQxnk1rhEO6ckRCNS73vQA',
    appId: '1:565467298061:ios:01cfa5775e34bfba6ad844',
    messagingSenderId: '565467298061',
    projectId: 'e-tiket-kapal-laut',
    storageBucket: 'e-tiket-kapal-laut.appspot.com',
    iosClientId: '565467298061-v8k9r19r8b3b8ud2sgh236kojv6c4it9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTiketKapalTa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJ548vDC5UXQxnk1rhEO6ckRCNS73vQA',
    appId: '1:565467298061:ios:01cfa5775e34bfba6ad844',
    messagingSenderId: '565467298061',
    projectId: 'e-tiket-kapal-laut',
    storageBucket: 'e-tiket-kapal-laut.appspot.com',
    iosClientId: '565467298061-v8k9r19r8b3b8ud2sgh236kojv6c4it9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTiketKapalTa',
  );
}
